using System;
using System.Collections.Generic;
using System.Data;

namespace TheTechIdea.Beep.DataBase.Helpers
{
    internal static class DataStreamer
    {
        public static IEnumerable<Dictionary<string, object>> Stream(IDataReader reader)
        {
            if (reader == null) yield break;
            using (reader)
            {
                int fieldCount = reader.FieldCount;
                while (reader.Read())
                {
                    var row = new Dictionary<string, object>(fieldCount, StringComparer.OrdinalIgnoreCase);
                    for (int i = 0; i < fieldCount; i++)
                    {
                        row[reader.GetName(i)] = reader.IsDBNull(i) ? null : reader.GetValue(i);
                    }
                    yield return row;
                }
            }
        }

        // The typed overload -- Stream(IDataReader, Type), MapRowToInstance, SetPropertyValue and
        // the static _propertyCache they shared -- was removed here. It had no callers: both live
        // read paths in RDBSource.Query.cs use the dictionary overload above and do their own
        // per-column conversion. Three things went with it:
        //
        //   * _propertyCache was a static ConcurrentDictionary keyed by Type with no eviction. The
        //     types RDBSource streams are Roslyn-generated by DMTypeBuilder, so a cache entry
        //     pinned the generated type and its assembly for the lifetime of the process.
        //   * SetPropertyValue ended in a completely empty catch, so a column that would not
        //     convert left the property at its default with nothing recorded anywhere.
        //   * Worse, it converted with Convert.ChangeType(value, prop.PropertyType) without
        //     unwrapping Nullable<>. ChangeType cannot target Nullable<T>, so every nullable
        //     property took the throw and silently kept its default -- and the empty catch is
        //     exactly why that was never noticed.
        //
        // Anything reinstating typed streaming should unwrap Nullable<> before converting and take
        // a reporting callback rather than swallowing failures.
    }
}